IF OBJECT_ID('dbo.Universities', 'U') IS NOT NULL
BEGIN 
	DROP TABLE Universities
END

CREATE TABLE Universities (
 id INT IDENTITY(1,1) PRIMARY KEY,
 uni_name VARCHAR(225) NULL,
 uni_acronym VARCHAR(5) NULL
);


INSERT INTO Universities (uni_name, uni_acronym)
OUTPUT inserted.*
VALUES
	('SINGAPORE MANAGEMENT UNIVERSITY', 'SMU'),
	('NANYANG TECHNOLOGY UNIVERSITY', 'NTU'),
	('NATIONAL UNIVERSITY SINGAPORE', 'NUS');